name: 'shopify_analytics'
version: '1.0.0'
config-version: 2

profile: 'shopify_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  shopify_analytics:
    staging:
      +materialized: view
      shopify:
        +schema: staging
      ads:
        +schema: staging
    facts:
      +materialized: incremental
      +unique_key: id
      +schema: analytics
    metrics:
      +materialized: view
      +schema: analytics
    attribution:
      +materialized: view
      +schema: analytics

vars:
  tenant_isolation_enforced: true
