name: 'markinsight'
version: '1.0.0'
config-version: 2

profile: 'markinsight'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  markinsight:
    raw_sources:
      +enabled: true
    staging:
      +materialized: view
      shopify:
        +schema: staging
      ads:
        +schema: staging
      facebook:
        +schema: staging
      google:
        +schema: staging
      tiktok:
        +schema: staging
      email:
        +schema: staging
      sms:
        +schema: staging
      dimensions:
        +materialized: table
        +schema: staging
    canonical:
      +materialized: incremental
      +unique_key: id
      +schema: analytics
      +on_schema_change: append_new_columns
    semantic_views:
      +materialized: view
      +schema: semantic
      +tags: ['semantic', 'governed']
    metrics:
      +materialized: view
      +schema: analytics
    attribution:
      +materialized: view
      +schema: analytics
    utils:
      +materialized: table
      +schema: utils
    marts:
      +materialized: table
      +schema: marts
      marketing:
        +materialized: table
        +schema: marts
        +tags: ['marketing', 'metrics']

data_tests:
  markinsight:
    # All data tests should fail the build by default
    +severity: error

vars:
  tenant_isolation_enforced: true

  # Per-source raw schema configuration
  # All default to airbyte_raw for backward compatibility with existing Airbyte setup.
  # Override when migrating to per-source schemas:
  #   dbt run --vars '{raw_shopify_schema: raw_shopify, raw_facebook_ads_schema: raw_facebook_ads}'
  raw_shopify_schema: airbyte_raw
  raw_facebook_ads_schema: airbyte_raw
  raw_google_ads_schema: airbyte_raw
  raw_tiktok_ads_schema: airbyte_raw
  raw_snapchat_ads_schema: airbyte_raw
  raw_email_schema: airbyte_raw
  raw_sms_schema: airbyte_raw
  platform_schema: platform

  # Lookback window configuration for incremental models
  # Controls how far back to look for late-arriving data during incremental runs
  # Override per-source as needed based on data latency characteristics
  lookback_days_default: 3
  lookback_days_shopify: 3
  lookback_days_meta_ads: 3
  lookback_days_google_ads: 3
  lookback_days_tiktok_ads: 3
  lookback_days_pinterest_ads: 3
  lookback_days_snap_ads: 3
  lookback_days_amazon_ads: 3
  lookback_days_klaviyo: 3
  lookback_days_ga4: 3
  lookback_days_recharge: 3

  # Rolling rebuild window configuration for v1 canonical models
  # Controls how far back to reprocess on incremental runs (business-date based)
  # Override per-source as needed based on data latency characteristics
  shopify_rebuild_days: 90
  ads_rebuild_days: 30
  email_rebuild_days: 30

  # Freshness SLAs — mirrors config/data_freshness_sla.yml. Keep both in sync.
  # dbt sources reference these via the get_freshness_threshold() macro.
  # Override the billing tier at runtime:  dbt source freshness --vars '{billing_tier: enterprise}'
  billing_tier: free
  freshness_sla:
    shopify_orders:
      free: {warn_after_minutes: 1440, error_after_minutes: 2880}
      growth: {warn_after_minutes: 360, error_after_minutes: 720}
      enterprise: {warn_after_minutes: 60, error_after_minutes: 120}
    facebook_ads:
      free: {warn_after_minutes: 1440, error_after_minutes: 2880}
      growth: {warn_after_minutes: 360, error_after_minutes: 720}
      enterprise: {warn_after_minutes: 60, error_after_minutes: 120}
    google_ads:
      free: {warn_after_minutes: 1440, error_after_minutes: 2880}
      growth: {warn_after_minutes: 360, error_after_minutes: 720}
      enterprise: {warn_after_minutes: 60, error_after_minutes: 120}
    tiktok_ads:
      free: {warn_after_minutes: 1440, error_after_minutes: 2880}
      growth: {warn_after_minutes: 360, error_after_minutes: 720}
      enterprise: {warn_after_minutes: 60, error_after_minutes: 120}
    snapchat_ads:
      free: {warn_after_minutes: 1440, error_after_minutes: 2880}
      growth: {warn_after_minutes: 360, error_after_minutes: 720}
      enterprise: {warn_after_minutes: 60, error_after_minutes: 120}
    email:
      free: {warn_after_minutes: 1440, error_after_minutes: 2880}
      growth: {warn_after_minutes: 720, error_after_minutes: 1440}
      enterprise: {warn_after_minutes: 360, error_after_minutes: 720}
    sms:
      free: {warn_after_minutes: 1440, error_after_minutes: 2880}
      growth: {warn_after_minutes: 720, error_after_minutes: 1440}
      enterprise: {warn_after_minutes: 360, error_after_minutes: 720}
