name: 'shopify_analytics'
version: '1.0.0'
config-version: 2

profile: 'shopify_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  shopify_analytics:
    staging:
      +materialized: view
      shopify:
        +schema: staging
      ads:
        +schema: staging
    facts:
      +materialized: incremental
      +unique_key: id
      +schema: analytics
    metrics:
      +materialized: view
      +schema: analytics
    attribution:
      +materialized: view
      +schema: analytics
    utils:
      +materialized: table
      +schema: utils
    marts:
      +materialized: table
      +schema: marts

data_tests:
  shopify_analytics:
    # All data tests should fail the build by default
    +severity: error

vars:
  tenant_isolation_enforced: true
  # Source schema configuration - override these when Airbyte/platform tables
  # are in different schemas than the defaults
  # Example: dbt run --vars '{airbyte_raw_schema: my_raw_schema, platform_schema: my_platform}'
  airbyte_raw_schema: airbyte_raw  # Schema containing _airbyte_raw_* tables
  platform_schema: platform  # Schema containing tenant_airbyte_connections table

  # Incremental lookback windows (in days) - per user story 7.7.1
  # These control how far back incremental models look for changed records
  # Default: 7 days. Override per-source as needed.
  fact_orders_lookback_days: 7
  fact_ad_spend_lookback_days: 7
  fact_campaign_performance_lookback_days: 7
