name: 'shopify_analytics'
version: '1.0.0'
config-version: 2

profile: 'shopify_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  shopify_analytics:
    staging:
      +materialized: view
      shopify:
        +schema: staging
      ads:
        +schema: staging
    facts:
      +materialized: incremental
      +unique_key: id
      +schema: analytics
    metrics:
      +materialized: view
      +schema: analytics
    attribution:
      +materialized: view
      +schema: analytics

tests:
  shopify_analytics:
    # Critical data quality tests should fail the build
    +severity: error
    # Freshness tests are critical - fail build if data is stale
    test_freshness:
      +severity: error
    # Volume anomaly tests are warnings - alert but don't fail build
    test_volume_anomaly:
      +severity: warn
    # Primary key and not_null tests are critical
    not_null:
      +severity: error
    unique:
      +severity: error
    relationships:
      +severity: error

vars:
  tenant_isolation_enforced: true
