version: 2

models:
  - name: fact_orders
    description: |
      Canonical fact table for Shopify orders.
      
      This is the source of truth for all order events. The table is incremental
      and processes new/updated orders based on airbyte_emitted_at.
      
      SECURITY: All rows are tenant-isolated via tenant_id.
    tests:
      - test_freshness:
          column_name: dbt_updated_at
          error_after_hours: 48
          config:
            severity: error
      - test_volume_anomaly:
          date_column: order_created_at
          min_daily_records: 1
          lookback_days: 7
          config:
            severity: warn
    columns:
      - name: id
        description: Surrogate key (MD5 hash of tenant_id + order_id)
        tests:
          - not_null
          - unique
      - name: order_id
        description: Shopify order ID (normalized, without gid:// prefix)
        tests:
          - not_null
      - name: order_name
        description: Order name/number from Shopify (e.g., #1001)
      - name: order_number
        description: Order number as integer
      - name: customer_email
        description: Customer email address
      - name: customer_id_raw
        description: Raw customer ID from Shopify
      - name: order_created_at
        description: Order creation timestamp (UTC)
        tests:
          - not_null
      - name: order_updated_at
        description: Order last update timestamp (UTC)
      - name: order_cancelled_at
        description: Order cancellation timestamp (UTC, nullable)
      - name: order_closed_at
        description: Order closure timestamp (UTC, nullable)
      - name: revenue
        description: Total order revenue (numeric)
        tests:
          - not_null
      - name: subtotal_price
        description: Subtotal before tax (numeric)
      - name: total_tax
        description: Total tax amount (numeric)
      - name: currency
        description: Currency code (uppercase, 3-letter)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CNY']
              config:
                where: "currency is not null"
      - name: financial_status
        description: Financial status (e.g., paid, pending, refunded)
      - name: fulfillment_status
        description: Fulfillment status (e.g., fulfilled, unfulfilled)
      - name: tags
        description: Order tags (comma-separated)
      - name: note
        description: Order notes
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"
      - name: airbyte_record_id
        description: Airbyte record ID for tracking
      - name: ingested_at
        description: Timestamp when record was ingested from Airbyte
        tests:
          - not_null
      - name: dbt_updated_at
        description: Timestamp when record was last updated by dbt
        tests:
          - not_null

  - name: fact_ad_spend
    description: |
      Canonical fact table for ad spend across all platforms (Meta Ads, Google Ads).
      
      This table unifies ad spend data from multiple ad platforms into a single
      source of truth. The table is incremental and processes new records based
      on airbyte_emitted_at.
      
      SECURITY: All rows are tenant-isolated via tenant_id.
    tests:
      - test_freshness:
          column_name: dbt_updated_at
          error_after_hours: 48
          config:
            severity: error
      - test_volume_anomaly:
          date_column: spend_date
          min_daily_records: 1
          lookback_days: 7
          config:
            severity: warn
    columns:
      - name: id
        description: Surrogate key (MD5 hash of tenant_id + platform + ad_account_id + campaign_id + ad_id + spend_date)
        tests:
          - not_null
          - unique
      - name: ad_account_id
        description: Ad account ID (platform-specific)
        tests:
          - not_null
      - name: campaign_id
        description: Campaign ID (platform-specific)
        tests:
          - not_null
      - name: adset_id
        description: Ad set/group ID (platform-specific, nullable for some platforms)
      - name: ad_id
        description: Ad ID (platform-specific, nullable)
      - name: spend_date
        description: Date of the spend (DATE)
        tests:
          - not_null
      - name: spend
        description: Amount spent (numeric, normalized currency)
        tests:
          - not_null
      - name: currency
        description: Currency code (uppercase, 3-letter)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CNY']
              config:
                where: "currency is not null"
      - name: platform
        description: Platform identifier (meta_ads or google_ads)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['meta_ads', 'google_ads']
              config:
                where: "platform is not null"
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"
      - name: airbyte_record_id
        description: Airbyte record ID for tracking
      - name: ingested_at
        description: Timestamp when record was ingested from Airbyte
        tests:
          - not_null
      - name: dbt_updated_at
        description: Timestamp when record was last updated by dbt
        tests:
          - not_null

  - name: fact_campaign_performance
    description: |
      Canonical fact table for campaign performance across all platforms (Meta Ads, Google Ads).
      
      This table unifies campaign-level performance metrics from multiple ad platforms
      into a single source of truth. The table is incremental and processes new records
      based on airbyte_emitted_at.
      
      SECURITY: All rows are tenant-isolated via tenant_id.
    tests:
      - test_freshness:
          column_name: dbt_updated_at
          error_after_hours: 48
          config:
            severity: error
      - test_volume_anomaly:
          date_column: performance_date
          min_daily_records: 1
          lookback_days: 7
          config:
            severity: warn
    columns:
      - name: id
        description: Surrogate key (MD5 hash of tenant_id + platform + ad_account_id + campaign_id + performance_date)
        tests:
          - not_null
          - unique
      - name: ad_account_id
        description: Ad account ID (platform-specific)
        tests:
          - not_null
      - name: campaign_id
        description: Campaign ID (platform-specific)
        tests:
          - not_null
      - name: campaign_name
        description: Campaign name
      - name: performance_date
        description: Date of the performance metrics (DATE)
        tests:
          - not_null
      - name: spend
        description: Amount spent (numeric, normalized currency)
        tests:
          - not_null
      - name: impressions
        description: Number of impressions (integer)
        tests:
          - not_null
      - name: clicks
        description: Number of clicks (integer)
        tests:
          - not_null
      - name: conversions
        description: Number of conversions (numeric)
        tests:
          - not_null
      - name: ctr
        description: Click-through rate (percentage, calculated)
      - name: cpc
        description: Cost per click (calculated)
      - name: cpa
        description: Cost per acquisition/conversion (calculated)
      - name: currency
        description: Currency code (uppercase, 3-letter)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CNY']
              config:
                where: "currency is not null"
      - name: platform
        description: Platform identifier (meta_ads or google_ads)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['meta_ads', 'google_ads']
              config:
                where: "platform is not null"
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"
      - name: airbyte_record_id
        description: Airbyte record ID for tracking
      - name: ingested_at
        description: Timestamp when record was ingested from Airbyte
        tests:
          - not_null
      - name: dbt_updated_at
        description: Timestamp when record was last updated by dbt
        tests:
          - not_null
