version: 2

models:
  - name: dim_ad_accounts
    description: >
      Dimension table for normalized ad account IDs across all platforms.
      Implements Option B ID normalization with deterministic internal IDs.
    columns:
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"

      - name: source
        description: Platform source identifier (meta_ads, google_ads, etc.)
        tests:
          - not_null
          - accepted_values:
              values: ['meta_ads', 'google_ads', 'tiktok_ads', 'pinterest_ads', 'snap_ads', 'amazon_ads']

      - name: platform_account_id
        description: Original platform-specific account ID
        tests:
          - not_null

      - name: internal_account_id
        description: Deterministic hash ID for cross-platform joins (MD5 of tenant_id|source|platform_account_id)
        tests:
          - not_null
          - unique

      - name: currency
        description: Account currency code

      - name: first_seen_at
        description: Earliest record timestamp for this account
        tests:
          - not_null

      - name: last_seen_at
        description: Most recent record timestamp for this account
        tests:
          - not_null

      - name: created_at
        description: Record creation timestamp

      - name: updated_at
        description: Record update timestamp

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - tenant_id
            - source
            - platform_account_id

  - name: dim_campaigns
    description: >
      Dimension table for normalized campaign IDs across all platforms.
      Implements Option B ID normalization with deterministic internal IDs.
    columns:
      - name: tenant_id
        description: Tenant identifier for data isolation
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"

      - name: source
        description: Platform source identifier (meta_ads, google_ads, etc.)
        tests:
          - not_null
          - accepted_values:
              values: ['meta_ads', 'google_ads', 'tiktok_ads', 'pinterest_ads', 'snap_ads', 'amazon_ads']

      - name: platform_campaign_id
        description: Original platform-specific campaign ID
        tests:
          - not_null

      - name: internal_campaign_id
        description: Deterministic hash ID for cross-platform joins (MD5 of tenant_id|source|platform_campaign_id)
        tests:
          - not_null
          - unique

      - name: platform_account_id
        description: Platform-specific account ID
        tests:
          - not_null

      - name: internal_account_id
        description: Links to dim_ad_accounts.internal_account_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_ad_accounts')
              field: internal_account_id

      - name: campaign_name
        description: Human-readable campaign name

      - name: first_seen_at
        description: Earliest record timestamp for this campaign
        tests:
          - not_null

      - name: last_seen_at
        description: Most recent record timestamp for this campaign
        tests:
          - not_null

      - name: created_at
        description: Record creation timestamp

      - name: updated_at
        description: Record update timestamp

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - tenant_id
            - source
            - platform_campaign_id
