version: 2

models:
  # ===========================================================================
  # ROAS v1 - Return on Ad Spend (Versioned)
  # ===========================================================================
  - name: roas_v1
    description: |
      ## ROAS v1 - Return on Ad Spend (Versioned Metric)

      **Registry:** `metrics/metric_registry.yaml`
      **Status:** `active`
      **Approval:** ANALYTICS-001

      ### Definition

      ```
      ROAS = SUM(revenue) / SUM(spend)
      ```

      ### Version Policy

      This is a VERSIONED metric. The formula is immutable once released.
      Any changes to the calculation require a new version (v2, v3, etc.).

      ### Drill-Down Hierarchy

      Supports drill-down from high-level to granular:
      - **channel**: Marketing channel (paid_social, paid_search)
      - **campaign**: Specific campaign performance
      - **adset**: Ad set / ad group level

      ### Edge Cases

      | Scenario | Behavior |
      |----------|----------|
      | Zero spend | Returns 0 (not NULL/infinity) |
      | Null spend | Treated as 0 |
      | Negative revenue | Included (reflects refunds) |
      | Multi-currency | Calculated per currency |

      ### Usage

      ```sql
      SELECT
        period_start,
        channel,
        roas,
        total_spend,
        total_revenue
      FROM roas_v1
      WHERE tenant_id = ?
        AND metric_version = 'v1'
        AND period_type = 'monthly'
        AND hierarchy_level = 'channel';
      ```

    config:
      tags: ['marts', 'metrics', 'roas', 'v1', 'versioned']

    columns:
      - name: id
        description: Unique identifier (MD5 hash of composite key)
        tests:
          - unique
          - not_null

      - name: metric_name
        description: Name of the metric (always 'roas' for this model)
        tests:
          - not_null
          - accepted_values:
              values: ['roas']

      - name: metric_version
        description: |
          Version of the metric formula.
          IMMUTABLE - changes require new version.
        tests:
          - not_null
          - accepted_values:
              values: ['v1']

      - name: metric_status
        description: Current lifecycle status of this metric version
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'deprecated', 'sunset']

      - name: tenant_id
        description: Tenant identifier (CRITICAL for multi-tenant isolation)
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"

      - name: period_type
        description: Time period granularity
        tests:
          - not_null
          - accepted_values:
              values: ['daily', 'weekly', 'monthly', 'all_time']

      - name: period_start
        description: Start date of the period

      - name: period_end
        description: End date of the period

      - name: currency
        description: ISO 4217 currency code

      - name: hierarchy_level
        description: Drill-down level (channel, campaign, adset)
        tests:
          - not_null
          - accepted_values:
              values: ['channel', 'campaign', 'adset']

      - name: channel
        description: Marketing channel

      - name: campaign_id
        description: Campaign identifier (null at channel level)

      - name: adset_id
        description: Ad set identifier (null at channel/campaign level)

      - name: total_spend
        description: Total advertising spend
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: total_revenue
        description: Total revenue (net)
        tests:
          - not_null

      - name: order_count
        description: Number of orders
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: roas
        description: |
          **CANONICAL ROAS (v1)**
          Formula: SUM(revenue) / SUM(spend)
          Returns 0 when spend = 0
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: cpc
        description: Cost per Click
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: cpm
        description: Cost per Mille (1000 impressions)
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: ctr
        description: Click-through Rate (percentage)
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: aov
        description: Average Order Value
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: dbt_updated_at
        description: Timestamp when record was last updated

    tests:
      # Version integrity test
      - dbt_utils.expression_is_true:
          expression: "metric_version = 'v1'"
          config:
            where: "1=1"

      # ROAS accuracy test
      - dbt_utils.expression_is_true:
          expression: |
            CASE
              WHEN total_spend > 0 THEN ABS(roas - (total_revenue / total_spend)) < 0.01
              ELSE roas = 0
            END

      # Divide-by-zero handling
      - dbt_utils.expression_is_true:
          expression: "roas = 0"
          config:
            where: "total_spend = 0"

  # ===========================================================================
  # CAC v1 - Customer Acquisition Cost (Versioned)
  # ===========================================================================
  - name: cac_v1
    description: |
      ## CAC v1 - Customer Acquisition Cost (Versioned Metric)

      **Registry:** `metrics/metric_registry.yaml`
      **Status:** `active`
      **Approval:** ANALYTICS-002

      ### Definition

      ```
      CAC = SUM(spend) / COUNT(new_customers)
      ```

      ### New Customer Definition (v1)

      - First order ever based on `customer_key` (pseudonymized)
      - Must be attributed to paid channel
      - All new customers counted (no exclusions in v1)

      ### Version Policy

      This is a VERSIONED metric. The formula is immutable once released.
      Any changes to the calculation require a new version (v2, v3, etc.).

      ### Hierarchy Note

      CAC is only meaningful at the **channel** level.
      At campaign/adset levels, `new_customers = 0` because attribution
      below channel level is not implemented in v1.

      ### Edge Cases

      | Scenario | Behavior |
      |----------|----------|
      | Zero customers | Returns 0 (not NULL/infinity) |
      | Null customers | Treated as 0 |
      | Multi-currency | Calculated per currency |
      | Duplicate customers | Counted once per customer_key |

      ### Usage

      ```sql
      SELECT
        period_start,
        channel,
        cac,
        new_customers,
        total_spend
      FROM cac_v1
      WHERE tenant_id = ?
        AND metric_version = 'v1'
        AND period_type = 'monthly'
        AND hierarchy_level = 'channel'
        AND cac > 0;  -- Only periods with acquisitions
      ```

    config:
      tags: ['marts', 'metrics', 'cac', 'v1', 'versioned']

    columns:
      - name: id
        description: Unique identifier (MD5 hash of composite key)
        tests:
          - unique
          - not_null

      - name: metric_name
        description: Name of the metric (always 'cac' for this model)
        tests:
          - not_null
          - accepted_values:
              values: ['cac']

      - name: metric_version
        description: |
          Version of the metric formula.
          IMMUTABLE - changes require new version.
        tests:
          - not_null
          - accepted_values:
              values: ['v1']

      - name: metric_status
        description: Current lifecycle status of this metric version
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'deprecated', 'sunset']

      - name: tenant_id
        description: Tenant identifier (CRITICAL for multi-tenant isolation)
        tests:
          - not_null
          - relationships:
              to: ref('_tenant_airbyte_connections')
              field: tenant_id
              config:
                where: "tenant_id is not null"

      - name: period_type
        description: Time period granularity
        tests:
          - not_null
          - accepted_values:
              values: ['daily', 'weekly', 'monthly', 'all_time']

      - name: period_start
        description: Start date of the period

      - name: period_end
        description: End date of the period

      - name: currency
        description: ISO 4217 currency code

      - name: hierarchy_level
        description: Drill-down level (channel, campaign, adset)
        tests:
          - not_null
          - accepted_values:
              values: ['channel', 'campaign', 'adset']

      - name: channel
        description: Marketing channel

      - name: campaign_id
        description: Campaign identifier (null at channel level)

      - name: adset_id
        description: Ad set identifier (null at channel/campaign level)

      - name: total_spend
        description: Total advertising spend
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: new_customers
        description: |
          Count of new customers (first order ever).
          Only populated at 'channel' hierarchy_level.
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: cac
        description: |
          **CANONICAL CAC (v1)**
          Formula: SUM(spend) / COUNT(new_customers)
          Returns 0 when new_customers = 0
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: customers_per_1k_spend
        description: Number of customers acquired per $1000 spent
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: dbt_updated_at
        description: Timestamp when record was last updated

    tests:
      # Version integrity test
      - dbt_utils.expression_is_true:
          expression: "metric_version = 'v1'"
          config:
            where: "1=1"

      # CAC accuracy test (at channel level where new_customers > 0)
      - dbt_utils.expression_is_true:
          expression: |
            CASE
              WHEN new_customers > 0 THEN ABS(cac - (total_spend / new_customers)) < 0.01
              ELSE cac = 0
            END
          config:
            where: "hierarchy_level = 'channel'"

      # Divide-by-zero handling
      - dbt_utils.expression_is_true:
          expression: "cac = 0"
          config:
            where: "new_customers = 0"

      # New customers only at channel level
      - dbt_utils.expression_is_true:
          expression: "new_customers = 0"
          config:
            where: "hierarchy_level IN ('campaign', 'adset')"
